#!/usr/bin/env python3
from plumbum import FG, local
from plumbum.cmd import docker

REGISTRY = local.env.get("REGISTRY_HOST", "docker.io")
REPO = local.env["DOCKER_REPO"]
SUFFIX = local.env.get("DOCKER_REPO_SUFFIX", "")
VERSION = local.env["DOCKER_TAG"]


def image_ref(registry, tag):
    return "%s/%s%s:%s" % (registry, REPO, SUFFIX, tag)


source = image_ref(local.env["LOCAL_REGISTRY"], VERSION)
dest_tags = [image_ref(REGISTRY, VERSION)]
if VERSION == local.env.get("LATEST_RELEASE"):
    latest = "alpine" if VERSION.endswith("-alpine") else "latest"
    dest_tags.append(image_ref(REGISTRY, latest))

docker["buildx", "imagetools", "inspect", source] & FG

# Login in Docker Hub or ghcr
docker(
    "login",
    "--username",
    local.env["REGISTRY_USERNAME"],
    "--password",
    local.env["REGISTRY_TOKEN"],
    REGISTRY,
)

promote = docker["buildx", "imagetools", "create"]
for dest in dest_tags:
    promote = promote["-t", dest]
(promote[source] & FG)
